# Generated by Django 5.1.15 on 2026-09-24 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transport_type",
                    models.CharField(
                        choices=[("bus", "Bus"), ("train", "Train")], max_length=5
                    ),
                ),
                ("travel_date", models.DateField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("HELD", "Held"),
                            ("PAYMENT_PENDING", "Payment Pending"),
                            ("CONFIRMED", "Confirmed"),
                            ("CANCELLED", "Cancelled"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                ("source", models.CharField(max_length=160)),
                ("destination", models.CharField(max_length=160)),
                ("source_code", models.CharField(blank=True, max_length=20)),
                ("destination_code", models.CharField(blank=True, max_length=20)),
                ("boarding_point", models.CharField(blank=True, max_length=200)),
                ("dropping_point", models.CharField(blank=True, max_length=200)),
                ("departure_time", models.TimeField(blank=True, null=True)),
                ("arrival_time", models.TimeField(blank=True, null=True)),
                ("vehicle_name", models.CharField(blank=True, max_length=200)),
                ("vehicle_number", models.CharField(blank=True, max_length=30)),
                ("vehicle_type", models.CharField(blank=True, max_length=40)),
                (
                    "passenger_fare",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "service_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "tax",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("offer_code", models.CharField(blank=True, max_length=30)),
                ("hold_expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BookingPassenger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=120)),
                ("age", models.PositiveIntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=10,
                    ),
                ),
                ("mobile", models.CharField(blank=True, max_length=15)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("id_type", models.CharField(blank=True, max_length=30)),
                ("id_number", models.CharField(blank=True, max_length=40)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="BookingSeat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=10)),
                ("coach_name", models.CharField(blank=True, max_length=10)),
                ("state", models.CharField(default="HELD", max_length=12)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
