# Generated by Django 5.1.15 on 2026-09-24 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0001_initial"),
        ("cities", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("operator", models.CharField(max_length=120)),
                (
                    "bus_type",
                    models.CharField(
                        choices=[
                            ("AC_SLEEPER", "AC Sleeper"),
                            ("NON_AC_SLEEPER", "Non AC Sleeper"),
                            ("AC_SEATER", "AC Seater"),
                            ("NON_AC_SEATER", "Non AC Seater"),
                            ("AC_DLX", "AC Deluxe"),
                        ],
                        default="AC_SLEEPER",
                        max_length=30,
                    ),
                ),
                ("total_seats", models.PositiveIntegerField(default=40)),
                ("rating", models.FloatField(default=4.0)),
                ("amenities", models.JSONField(blank=True, default=list)),
                ("is_ac", models.BooleanField(default=True)),
                ("is_sleeper", models.BooleanField(default=True)),
                ("image_url", models.URLField(blank=True)),
            ],
            options={
                "verbose_name_plural": "buses",
                "ordering": ["operator", "name"],
            },
        ),
        migrations.CreateModel(
            name="BusSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("boarding_point", models.CharField(max_length=200)),
                ("boarding_time", models.TimeField()),
                ("dropping_point", models.CharField(max_length=200)),
                ("dropping_time", models.TimeField()),
                ("duration_minutes", models.PositiveIntegerField()),
                ("base_fare", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("available_days", models.CharField(default="1234567", max_length=30)),
                ("rating", models.FloatField(default=4.0)),
                ("reviews_count", models.PositiveIntegerField(default=0)),
                (
                    "bus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="buses.bus",
                    ),
                ),
                (
                    "destination_city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bus_schedules_to",
                        to="cities.city",
                    ),
                ),
                (
                    "source_city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bus_schedules_from",
                        to="cities.city",
                    ),
                ),
            ],
            options={
                "ordering": ["boarding_time"],
            },
        ),
        migrations.CreateModel(
            name="BusSeat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seat_number", models.CharField(max_length=10)),
                ("row", models.PositiveIntegerField()),
                ("floor", models.PositiveIntegerField(default=1)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("HELD", "Held"),
                            ("BOOKED", "Booked"),
                            ("UNAVAILABLE", "Unavailable"),
                        ],
                        default="AVAILABLE",
                        max_length=12,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female"), ("", "General")],
                        default="",
                        max_length=10,
                    ),
                ),
                ("hold_expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "booked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bus_seats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "locked_booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="locked_bus_seats",
                        to="bookings.booking",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seats",
                        to="buses.busschedule",
                    ),
                ),
            ],
            options={
                "ordering": ["row", "seat_number"],
                "unique_together": {("schedule", "seat_number")},
            },
        ),
    ]
