# Generated by Django 5.1.15 on 2026-09-24 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0001_initial"),
        ("cities", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Train",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=160)),
                ("train_type", models.CharField(default="Express", max_length=30)),
                ("runs_on", models.CharField(default="1234567", max_length=30)),
                ("rating", models.FloatField(default=4.2)),
            ],
            options={
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="TrainSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("travel_date", models.DateField()),
                ("duration_minutes", models.PositiveIntegerField()),
                ("running_days", models.CharField(default="1234567", max_length=30)),
                (
                    "base_fare",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("distance_km", models.FloatField(default=0)),
                (
                    "destination_station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="train_schedules_to",
                        to="cities.station",
                    ),
                ),
                (
                    "source_station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="train_schedules_from",
                        to="cities.station",
                    ),
                ),
                (
                    "train",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="trains.train",
                    ),
                ),
            ],
            options={
                "ordering": ["travel_date"],
            },
        ),
        migrations.CreateModel(
            name="TrainCoach",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10)),
                (
                    "coach_class",
                    models.CharField(
                        choices=[
                            ("SL", "Sleeper"),
                            ("3A", "AC 3 Tier"),
                            ("2A", "AC 2 Tier"),
                            ("1A", "AC First Class"),
                            ("CC", "AC Chair Car"),
                            ("2S", "Second Sitting"),
                        ],
                        max_length=4,
                    ),
                ),
                ("total_berths", models.PositiveIntegerField()),
                ("class_fare", models.DecimalField(decimal_places=2, max_digits=10)),
                ("available", models.PositiveIntegerField(default=0)),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coaches",
                        to="trains.trainschedule",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("schedule", "name")},
            },
        ),
        migrations.CreateModel(
            name="TrainBerth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("berth_number", models.CharField(max_length=6)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("SL", "Sleeper"),
                            ("3A", "AC 3 Tier"),
                            ("2A", "AC 2 Tier"),
                            ("1A", "AC First Class"),
                            ("CC", "AC Chair Car"),
                            ("2S", "Second Sitting"),
                        ],
                        max_length=4,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("HELD", "Held"),
                            ("BOOKED", "Booked"),
                            ("UNAVAILABLE", "Unavailable"),
                        ],
                        default="AVAILABLE",
                        max_length=12,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female"), ("", "General")],
                        default="",
                        max_length=10,
                    ),
                ),
                ("hold_expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "booked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="train_berths",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "locked_booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="locked_train_berths",
                        to="bookings.booking",
                    ),
                ),
                (
                    "coach",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="berths",
                        to="trains.traincoach",
                    ),
                ),
            ],
            options={
                "ordering": ["berth_number"],
                "unique_together": {("coach", "berth_number")},
            },
        ),
        migrations.CreateModel(
            name="TrainStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                ("distance_km", models.FloatField(default=0)),
                ("arrival_time", models.TimeField(blank=True, null=True)),
                ("departure_time", models.TimeField(blank=True, null=True)),
                ("platform", models.CharField(blank=True, max_length=10)),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cities.station"
                    ),
                ),
                (
                    "train",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route",
                        to="trains.train",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("train", "station")},
            },
        ),
    ]
